#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pkill -USR1 -x sxhkd &
pkill picom &

killall dunst
dunst -conf ~/.config/dunst/dunstrc &

########################################################
# detectar el numero de monitores
SCREEN=$(xrandr | grep " connected " | wc -l)
# la variable SCREEN valdría 1, 2, 3, etc, dependiendo del
# numero de monitores que detecte el comando xrandr
 
########################################################
# esto sería sin el monitor externo
if [ $SCREEN -eq 1 ]; then
    
    # asignar los 10 workspaces a la pantalla interna
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
    
fi
 
########################################################
# y con 2 monitores
if [ $SCREEN -eq 2 ]; then
# Resolución de las pantallas con script creado con arandr
 
$HOME/.screenlayout/bspwm-twoscreens.sh
    # o directo con este comando
    xrandr --output eDP1 --mode 1920x1080 --pos 0x722 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output VIRTUAL1 --off
    # xrandr --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-1 --mode 1440x900 --pos 1366x0 --rotate normal --output HDMI-2 --off
    
    # asignar los workspaces a cada pantalla
    bspc monitor eDP1 -d 1 2 3 4
    bspc monitor HDMI1 -d 5 6 7 8
 
fi
 
# adicional se deben modificar las barras de polybar
# dependiendo del numero de monitores
# ver archivo launch.sh en carpeta de polybar

bspc config border_width         0
bspc config window_gap          10

bspc config normal_border_color 	"#00396d"
bspc config focused_border_color	"#0098dc"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart Applications
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh &
